### ISSUE TITLE
using ESTIMATE on tumor thats not on the reference

### ISSUE THREAD

**Issue by chrkuo** [KaiAragaki/tidyestimate#12]
can I run ESTIMATE on a tumor that's not on the reference tumor. I am studying pediatric tumor cancer and would like to estimate stromal/immune

**Comment by KaiAragaki** [comment]
Hi, what exactly do you mean 'not on the reference tumor'?

**Comment by chrkuo** [comment]
@KaiAragaki  i might have misunderstood the ESTIMATE package but I. was under the impression that ESTIMATE package uses mostly adult cancer tumors to create this reference of immune/stromal/tumor purity score. since I am studying pediatric cancer would the results be altered assuming Tidyestimate is essentially the same thing

**Comment by KaiAragaki** [comment]
Ah, I see. If you have reason to believe that pediatric tumors would express signatures of stromal and immune infiltration despite being pure, then this could be an issue. However, so long as you take the assumption that a 'pure' pediatric tumor will look like a 'pure' adult tumor, you should be able to apply it to both types. 

Unless you are using Affymetrix data, you won't be able to get an absolute purity score. However, you can still get a relative purity score to compare between samples in you cohort.

**Comment by chrkuo** [comment]
@KaiAragaki 

Thanks for bringing that up - that was what my next question is: for visium 10x spatial transcriptomic assays is it affymetrix data? 

additionally once i get the score is it possible map it into spatial context like this?

<img width="1387" alt="image" src="https://github.com/KaiAragaki/tidyestimate/assets/119452428/6e48af45-e3fe-44a3-8b61-eaa44dcab856">

**Comment by KaiAragaki** [comment]
No, affy data is array-based rna expression. 

As for the figure, you might be able to apply the signature to every spot to assign it a score, treating each spot as a sample. But I'm not entirely sure how I would go about doing that. It's unclear what they did in this figure to get these scores.

**Comment by chrkuo** [comment]
@KaiAragaki 

I used the tidyestimate to generate the scores on all the RNA counts in my spatial data and have this dataframe:

<img width="558" alt="image" src="https://github.com/KaiAragaki/tidyestimate/assets/119452428/d49fd21f-33d7-42eb-acef-b44161dee85d">


I was wondering if you know how I can then apply these scores back into the spot of my object and then plot it?

**Comment by KaiAragaki** [comment]
I think this may be a bit beyond the purview of a tidyestimate issue, but one think that you might try is by supplying each column as a 'gene' in your original dataset and then using Seurat's feature plots to visualize it. You might also be able to store it as colData, but I forget how Seurat objects work (assuming you are using a Seurat object) and how similar they are to SummarizedExperiment objects.
