### ISSUE TITLE
ESTIMATE on single-cell RNA-seq

### ISSUE THREAD

**Issue by lmasatti** [KaiAragaki/tidyestimate#13]
Hi Kai, 

I was wondering if estimate scores can be used to annotate cells of single-cell experiment, by keeping the maximum of the three scores as a indicator of cell type. 
What do you think? 

Thank you in advance, 
Laura

**Comment by KaiAragaki** [comment]
Hi Laura!

I feel that with single cell data, you don't really need ESTIMATE as much. ESTIMATE is good for inferring tumor purity in absence of knowing exactly what's going on inside, but if you have single cell data, you DO know exactly what cells are immune cells and which are stromal (or at least, you can find out). For annotation of single cells, you can't go wrong with Seurat - particularly this part of their vignette: https://satijalab.org/seurat/articles/pbmc3k_tutorial#assigning-cell-type-identity-to-clusters. There's also monocle (https://cole-trapnell-lab.github.io/monocle3/) which I'm less familiar with, but both should get you to the same place.
